# -*- coding: utf-8 -*-
"""langchain-aam-zindagi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1USSFJZX9l8yBqyiGxDVdyjP6Tgr5Dh_L
"""

import random
class NakliLLM:

    def __init__(self):
        print("LLM created")

    def predict(self, prompt):

        reponse_list = [
            "Delhi is the capital of India",
            "IPL is cricket league in India",
            "AI stands for Artificial Intelligence"
        ]

        return {'response': random.choice(reponse_list)}

class NakliPromptTemplate:
  def __init__(self, template, input_variables):
    self.template = template
    self.input_variables = input_variables

  def format(self,input_dict):
    return self.template.format(**input_dict)

template = NakliPromptTemplate(
    template="What a {length} poem about {topic}?",
    input_variables=["length","topic"]
)

template.format({"length":"short","topic":"india"})

prompt = template.format({"length":"short","topic":"india"})

llm  = NakliLLM()

llm.predict(prompt)

class NakliChain:
  def __init__(self,llm,prompt):
    self.llm = llm
    self.prompt = prompt

  def run(self, input_dict):
    final_prompt = self.prompt.format(input_dict)
    result  = self.llm.predict(final_prompt)
    return result['response']

template = NakliPromptTemplate(
    template="What a {length} poem about {topic}?",
    input_variables=["length","topic"]
)

llm = NakliLLM()

chain = NakliChain(llm,template)

chain.run({"length":"short","topic":"india"})













