# -*- coding: utf-8 -*-
"""langchain-mentos-zindagi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QV84TpQ9hBXV5kUJk8eFwbISB_B_13KI
"""

from abc import ABC ,abstractmethod

class Runnable(ABC):
    @abstractmethod
    def invoke(self, input_data):
      pass

import random
class NakliLLM(Runnable):

    def __init__(self):
        print("LLM created")

    def invoke(self, prompt):
      reponse_list = [
            "Delhi is the capital of India",
            "IPL is cricket league in India",
            "AI stands for Artificial Intelligence"
        ]
      return {'response': random.choice(reponse_list)}

    def predict(self, prompt):

      reponse_list = [
            "Delhi is the capital of India",
            "IPL is cricket league in India",
            "AI stands for Artificial Intelligence"
        ]

      return {'response': random.choice(reponse_list)}

class NakliPromptTemplate(Runnable):
  def __init__(self, template, input_variables):
    self.template = template
    self.input_variables = input_variables

  def invoke(self, input_dict):
    return self.template.format(**input_dict)

  def format(self,input_dict):
    return self.template.format(**input_dict)

class NakliStrOutputParser(Runnable):
  def __init__(self):
    pass

  def invoke(self, input_data):
    return input_data['response']

class RunnableConnector(Runnable):

  def __init__(self,runnable_list):
    self.runnable_list = runnable_list

  def invoke(self, input_data):

    for runnable in self.runnable_list:
      input_data = runnable.invoke(input_data)

    return input_data

template = NakliPromptTemplate(
    template="What a {length} poem about {topic}?",
    input_variables=["length","topic"]
)

llm = NakliLLM()

parser = NakliStrOutputParser()

chain = RunnableConnector([template,llm,parser])

chain.invoke({"length":"long","topic":"AI"})

template1  = NakliPromptTemplate(
    template="Write a joke about {topic}",
    input_variables=["topic"]
)
template2  = NakliPromptTemplate(
    template="explain the following joke {response}",
    input_variables=["response"]
)

llm  = NakliLLM()
parser = NakliStrOutputParser()

chain1  = RunnableConnector([template1,llm])
chain2  = RunnableConnector([template2,llm,parser])

final_chain = RunnableConnector([chain1,chain2])

final_chain.invoke({"topic":"cricket"})

